file(READ ${DATA_PATH} PROCESSED_DATA)
string(REPLACE "\\" "\\\\" PROCESSED_DATA "${PROCESSED_DATA}")
string(REPLACE "\"" "\\\"" PROCESSED_DATA "${PROCESSED_DATA}")
string(REPLACE "\n" "\\n" PROCESSED_DATA "${PROCESSED_DATA}")

configure_file(${TEMPLATE_PATH} ${OUTPUT_PATH})